### ISSUE TITLE
extract 

### ISSUE THREAD

**Issue by Bucerella** [jorgesarabia/flutter_coverage#1]
Hi Jorge. I want to extract; models, widgets tests. How I do it? any have idea? I don't want coverage report models & widgets and I want to get a coverage percentage.

**Comment by jorgesarabia** [comment]
> Hi Jorge. I want to extract; models, widgets tests. How I do it? any have idea? I don't want coverage report models & widgets and I want to get a coverage percentage.

Hi Bucerella, do you want to separate the code coverage of models and widgets? 
I don't know if that is possible. But if the project is built by layers you can get an idea of the percentage covered looking at the coverage report. It will not be so accurate, but you can get a good approximation.

The images below show an example. In the first one, there is a widget folder. Into that folder are many widgets, I use the BLoC pattern, so, the business logic is in another class and looking at the report (image 2) I can figure myself the amount of coverage of the widgets.

![Captura de pantalla de 2019-12-16 09-55-08](https://user-images.githubusercontent.com/6399992/70908832-f0253500-1fea-11ea-9da0-6e9299becde6.png)

![Captura de pantalla de 2019-12-16 10-01-57](https://user-images.githubusercontent.com/6399992/70908900-177c0200-1feb-11ea-83fd-d73f6a622f12.png)


Hope this will useful for you!
